### ISSUE TITLE
Problem Windows, Bitbucket zip archive

### ISSUE THREAD

**Issue by paulkorman** [spatools/grunt-html-build#84]
grunt-html-build does not replace <-! build ->...<-! / build ->
I used the command for all the html files:
`unix2dos *.html`

**Comment by SomaticIT** [comment]
Your problem is the same as #82.
It will be fixed in next release.
Thanks

**Comment by SomaticIT** [comment]
Hi,
This issue has been fixed in release `0.7.0`.
You can now update your `grunt-html-build` package to fix this issue.

This release introduces a new `EOL` option which can be provided by target.
If this option is not provided, the module will automatically detect `EOL` from specified input file.

Hope it helps.
Thanks
